//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./AboutUsService_types');
//HELPER FUNCTIONS AND STRUCTURES

k.thrift.AboutUsService_selectAboutUs_args = function(args) {
  this.id = null;
  if (args) {
    if (args.id !== undefined && args.id !== null) {
      this.id = args.id;
    }
  }
};
k.thrift.AboutUsService_selectAboutUs_args.prototype = {};
k.thrift.AboutUsService_selectAboutUs_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.id = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

k.thrift.AboutUsService_selectAboutUs_args.prototype.write = function(output) {
  output.writeStructBegin('AboutUsService_selectAboutUs_args');
  if (this.id !== null && this.id !== undefined) {
    output.writeFieldBegin('id', Thrift.Type.I32, 1);
    output.writeI32(this.id);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

k.thrift.AboutUsService_selectAboutUs_result = function(args) {
  this.success = null;
  this.ae = null;
  if (args instanceof ttypes.AboutUsException) {
    this.ae = args;
    return;
  }
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.AboutUs(args.success);
    }
    if (args.ae !== undefined && args.ae !== null) {
      this.ae = args.ae;
    }
  }
};
k.thrift.AboutUsService_selectAboutUs_result.prototype = {};
k.thrift.AboutUsService_selectAboutUs_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.AboutUs();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.ae = new ttypes.AboutUsException();
        this.ae.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

k.thrift.AboutUsService_selectAboutUs_result.prototype.write = function(output) {
  output.writeStructBegin('AboutUsService_selectAboutUs_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.ae !== null && this.ae !== undefined) {
    output.writeFieldBegin('ae', Thrift.Type.STRUCT, 1);
    this.ae.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

k.thrift.AboutUsServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
k.thrift.AboutUsServiceClient.prototype = {};
k.thrift.AboutUsServiceClient.prototype.seqid = function() { return this._seqid; }
k.thrift.AboutUsServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
k.thrift.AboutUsServiceClient.prototype.selectAboutUs = function(id, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_selectAboutUs(id);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_selectAboutUs(id);
  }
};

k.thrift.AboutUsServiceClient.prototype.send_selectAboutUs = function(id) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('AboutUsService:selectAboutUs', Thrift.MessageType.CALL, this.seqid());
  var args = new k.thrift.AboutUsService_selectAboutUs_args();
  args.id = id;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

k.thrift.AboutUsServiceClient.prototype.recv_selectAboutUs = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new k.thrift.AboutUsService_selectAboutUs_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.ae) {
    return callback(result.ae);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('selectAboutUs failed: unknown result');
};
k.thrift.AboutUsServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
k.thrift.AboutUsServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

k.thrift.AboutUsServiceProcessor.prototype.process_selectAboutUs = function(seqid, input, output) {
  var args = new k.thrift.AboutUsService_selectAboutUs_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.selectAboutUs.length === 1) {
    Q.fcall(this._handler.selectAboutUs, args.id)
      .then(function(result) {
        var result = new k.thrift.AboutUsService_selectAboutUs_result({success: result});
        output.writeMessageBegin("selectAboutUs", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        if (err instanceof ttypes.AboutUsException) {
          var result = new k.thrift.AboutUsService_selectAboutUs_result(err);
          output.writeMessageBegin("selectAboutUs", Thrift.MessageType.REPLY, seqid);
        } else {
          var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("selectAboutUs", Thrift.MessageType.EXCEPTION, seqid);
        }
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.selectAboutUs(args.id, function (err, result) {
      if (err == null || err instanceof ttypes.AboutUsException) {
        var result = new k.thrift.AboutUsService_selectAboutUs_result((err != null ? err : {success: result}));
        output.writeMessageBegin("selectAboutUs", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("selectAboutUs", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

